blank_issues_enabled: false
contact_links:
  - name: Marketplace listing
    url: https://marketplace.visualstudio.com/items?itemName=thrsouza.emerald-minimal-theme
    about: View, rate, or review the theme on the VS Code Marketplace.
